//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicalstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDrug()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
        }
    
        public int drug_id { get; set; }
        public string drug_name { get; set; }
        public string manufacture_name { get; set; }
        public Nullable<System.DateTime> manufacture_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
    }
}
